"""
Image handler implementations for Fal.ai MCP Server.

Contains: generate_image, generate_image_structured, generate_image_from_image
"""

import asyncio
import json
from typing import Any, Dict, List

from loguru import logger
from mcp.types import TextContent

from fal_mcp_server.model_registry import ModelRegistry
from fal_mcp_server.queue.base import QueueStrategy

# Models that require {"width": N, "height": N} instead of a string alias
_PIXEL_SIZE_MODELS = {
    "openai/gpt-image-2",
    "openai/gpt-image-2/edit",
    "fal-ai/gpt-image-1.5",
    "fal-ai/gpt-image-1.5/edit",
}

# Standard string aliases mapped to (w_ratio, h_ratio)
_ALIAS_RATIOS: Dict[str, tuple] = {
    "square":         (1, 1),
    "square_hd":      (1, 1),
    "landscape_4_3":  (4, 3),
    "landscape_16_9": (16, 9),
    "portrait_3_4":   (3, 4),
    "portrait_9_16":  (9, 16),
}


def _compute_pixel_size(w_ratio: int, h_ratio: int, long_side: int) -> Dict[str, int]:
    """Return {width, height} from aspect ratio and long-side pixels."""
    if w_ratio >= h_ratio:
        return {"width": long_side, "height": round(long_side * h_ratio / w_ratio)}
    return {"width": round(long_side * w_ratio / h_ratio), "height": long_side}


def _resolve_image_size(model_id: str, arguments: Dict[str, Any]) -> Any:
    """Resolve image size from arguments with priority:
    1. width + height  → pixel object (always)
    2. aspect + size_px → compute pixel object from ratio (size_px = long side)
    3. image_size alias → pixel object for pixel-only models, string otherwise
    """
    if "width" in arguments and "height" in arguments:
        return {"width": arguments["width"], "height": arguments["height"]}

    if "aspect" in arguments:
        w_ratio, h_ratio = map(int, arguments["aspect"].split(":"))
        return _compute_pixel_size(w_ratio, h_ratio, arguments.get("size_px", 1024))

    alias = arguments.get("image_size", "landscape_16_9")
    needs_pixels = any(
        model_id == m or model_id.startswith(m + "/") for m in _PIXEL_SIZE_MODELS
    )
    if needs_pixels:
        ratios = _ALIAS_RATIOS.get(alias, (4, 3))
        return _compute_pixel_size(ratios[0], ratios[1], 1024)
    return alias


async def handle_generate_image(
    arguments: Dict[str, Any],
    registry: ModelRegistry,
    queue_strategy: QueueStrategy,
) -> List[TextContent]:
    """Handle the generate_image tool."""
    model_input = arguments.get("model", "flux_schnell")
    try:
        model_id = await registry.resolve_model_id(model_input)
    except ValueError as e:
        return [
            TextContent(
                type="text",
                text=f"❌ {e}. Use list_models to see available options.",
            )
        ]

    fal_args: Dict[str, Any] = {
        "prompt": arguments["prompt"],
        "image_size": _resolve_image_size(model_id, arguments),
        "num_images": arguments.get("num_images", 1),
    }

    # Add optional parameters
    if "negative_prompt" in arguments:
        fal_args["negative_prompt"] = arguments["negative_prompt"]
    if "seed" in arguments:
        fal_args["seed"] = arguments["seed"]
    if "enable_safety_checker" in arguments:
        fal_args["enable_safety_checker"] = arguments["enable_safety_checker"]
    if "output_format" in arguments:
        fal_args["output_format"] = arguments["output_format"]

    # Use fast execution (no queue) for image generation
    try:
        result = await queue_strategy.execute_fast(model_id, fal_args)
    except Exception as e:
        logger.error("Image generation failed: %s", e)
        return [
            TextContent(
                type="text",
                text=f"❌ Image generation failed: {e}",
            )
        ]

    # Check for error in response
    if "error" in result:
        error_msg = result.get("error", "Unknown error")
        logger.error("Image generation failed for %s: %s", model_id, error_msg)
        return [
            TextContent(
                type="text",
                text=f"❌ Image generation failed: {error_msg}",
            )
        ]

    images = result.get("images", [])
    if not images:
        logger.warning("Image generation returned no images. Model: %s", model_id)
        return [
            TextContent(
                type="text",
                text=f"❌ No images were generated by {model_id}. The prompt may have been filtered.",
            )
        ]

    # Extract URLs safely
    try:
        urls = [img["url"] for img in images]
    except (KeyError, TypeError) as e:
        logger.error("Malformed image response from %s: %s", model_id, e)
        return [
            TextContent(
                type="text",
                text=f"❌ Image generation completed but response was malformed: {e}",
            )
        ]

    response = f"🎨 Generated {len(urls)} image(s) with {model_id}:\n\n"
    for i, url in enumerate(urls, 1):
        response += f"Image {i}: {url}\n"
    return [TextContent(type="text", text=response)]


async def handle_generate_image_structured(
    arguments: Dict[str, Any],
    registry: ModelRegistry,
    queue_strategy: QueueStrategy,
) -> List[TextContent]:
    """Handle the generate_image_structured tool."""
    model_input = arguments.get("model", "flux_schnell")
    try:
        model_id = await registry.resolve_model_id(model_input)
    except ValueError as e:
        return [
            TextContent(
                type="text",
                text=f"❌ {e}. Use list_models to see available options.",
            )
        ]

    # Build structured JSON prompt from arguments
    structured_prompt: Dict[str, Any] = {}

    # Required field
    structured_prompt["scene"] = arguments["scene"]

    # Optional structured fields
    for field in [
        "subjects",
        "style",
        "color_palette",
        "lighting",
        "mood",
        "background",
        "composition",
        "camera",
        "effects",
    ]:
        if field in arguments:
            structured_prompt[field] = arguments[field]

    # Convert structured prompt to JSON string
    json_prompt = json.dumps(structured_prompt, indent=2)

    fal_args: Dict[str, Any] = {
        "prompt": json_prompt,
        "image_size": _resolve_image_size(model_id, arguments),
        "num_images": arguments.get("num_images", 1),
    }

    # Add optional generation parameters
    if "negative_prompt" in arguments:
        fal_args["negative_prompt"] = arguments["negative_prompt"]
    if "seed" in arguments:
        fal_args["seed"] = arguments["seed"]
    if "enable_safety_checker" in arguments:
        fal_args["enable_safety_checker"] = arguments["enable_safety_checker"]
    if "output_format" in arguments:
        fal_args["output_format"] = arguments["output_format"]

    # Use fast execution with timeout protection
    logger.info("Starting structured image generation with %s", model_id)
    try:
        result = await asyncio.wait_for(
            queue_strategy.execute_fast(model_id, fal_args),
            timeout=60,
        )
    except asyncio.TimeoutError:
        logger.error("Structured image generation timed out for %s", model_id)
        return [
            TextContent(
                type="text",
                text=f"❌ Image generation timed out after 60 seconds with {model_id}. Please try again.",
            )
        ]

    # Check for error in response
    if "error" in result:
        error_msg = result.get("error", "Unknown error")
        logger.error(
            "Structured image generation failed for %s: %s", model_id, error_msg
        )
        return [
            TextContent(
                type="text",
                text=f"❌ Image generation failed: {error_msg}",
            )
        ]

    images = result.get("images", [])
    if not images:
        logger.warning(
            "Structured image generation returned no images. Model: %s",
            model_id,
        )
        return [
            TextContent(
                type="text",
                text=f"❌ No images were generated by {model_id}. The prompt may have been filtered or the request format was invalid.",
            )
        ]

    # Extract URLs safely
    try:
        urls = [img["url"] for img in images]
    except (KeyError, TypeError) as e:
        logger.error("Malformed image response from %s: %s", model_id, e)
        return [
            TextContent(
                type="text",
                text=f"❌ Image generation completed but response was malformed: {e}",
            )
        ]

    response = (
        f"🎨 Generated {len(urls)} image(s) with {model_id} (structured prompt):\n\n"
    )
    for i, url in enumerate(urls, 1):
        response += f"Image {i}: {url}\n"
    return [TextContent(type="text", text=response)]


async def handle_generate_image_from_image(
    arguments: Dict[str, Any],
    registry: ModelRegistry,
    queue_strategy: QueueStrategy,
) -> List[TextContent]:
    """Handle the generate_image_from_image tool."""
    model_input = arguments.get("model", "fal-ai/flux/dev/image-to-image")
    try:
        model_id = await registry.resolve_model_id(model_input)
    except ValueError as e:
        return [
            TextContent(
                type="text",
                text=f"❌ {e}. Use list_models to see available options.",
            )
        ]

    # Both image_url and prompt are required
    img2img_args: Dict[str, Any] = {
        "image_url": arguments["image_url"],
        "prompt": arguments["prompt"],
        "strength": arguments.get("strength", 0.75),
        "num_images": arguments.get("num_images", 1),
    }

    # Add optional parameters
    if "negative_prompt" in arguments:
        img2img_args["negative_prompt"] = arguments["negative_prompt"]
    if "seed" in arguments:
        img2img_args["seed"] = arguments["seed"]
    if "enable_safety_checker" in arguments:
        img2img_args["enable_safety_checker"] = arguments["enable_safety_checker"]
    if "output_format" in arguments:
        img2img_args["output_format"] = arguments["output_format"]

    logger.info(
        "Starting image-to-image transformation with %s from %s",
        model_id,
        (
            arguments["image_url"][:50] + "..."
            if len(arguments["image_url"]) > 50
            else arguments["image_url"]
        ),
    )

    # Use fast execution with timeout protection
    try:
        result = await asyncio.wait_for(
            queue_strategy.execute_fast(model_id, img2img_args),
            timeout=60,
        )
    except asyncio.TimeoutError:
        logger.error(
            "Image-to-image transformation timed out after 60s. Model: %s",
            model_id,
        )
        return [
            TextContent(
                type="text",
                text=f"❌ Image transformation timed out after 60 seconds with {model_id}. Please try again.",
            )
        ]
    except Exception as e:
        logger.exception("Image-to-image transformation failed: %s", e)
        return [
            TextContent(
                type="text",
                text=f"❌ Image transformation failed: {e}",
            )
        ]

    # Check for error in response
    if "error" in result:
        error_msg = result.get("error", "Unknown error")
        logger.error(
            "Image-to-image transformation failed for %s: %s",
            model_id,
            error_msg,
        )
        return [
            TextContent(
                type="text",
                text=f"❌ Image transformation failed: {error_msg}",
            )
        ]

    images = result.get("images", [])
    if not images:
        logger.warning(
            "Image-to-image transformation returned no images. Model: %s",
            model_id,
        )
        return [
            TextContent(
                type="text",
                text=f"❌ No images were generated by {model_id}. The source image may have been filtered.",
            )
        ]

    # Extract URLs safely
    try:
        urls = [img["url"] for img in images]
    except (KeyError, TypeError) as e:
        logger.error("Malformed image response from %s: %s", model_id, e)
        return [
            TextContent(
                type="text",
                text=f"❌ Image transformation completed but response was malformed: {e}",
            )
        ]

    response = f"🎨 Transformed image with {model_id}:\n\n"
    response += f"**Source**: {arguments['image_url'][:50]}...\n\n"
    for i, url in enumerate(urls, 1):
        response += f"Result {i}: {url}\n"
    return [TextContent(type="text", text=response)]
